
hci0: sensor_emulado.js
	sudo BLENO_HCI_DEVICE_ID=0 BLENO_ADVERTISING_INTERVAL=1000 node sensor_emulado.js

hci1: sensor_emulado.js
	sudo BLENO_HCI_DEVICE_ID=1 BLENO_ADVERTISING_INTERVAL=1000 node sensor_emulado.js